version: "3.7"
services:
  db:
    container_name: postgre
    image: postgres
    env_file:
      - .env
    restart: always
    ports:
      - 5432:5432
  node-app:
    container_name: backend
    build: backend/
    env_file:
      - .env
    ports:
      - "5000:5000"
  react-app:
    container_name: frontend
    build: frontend/
    env_file:
      - .env
    ports:
      - "3000:3000"